@startuml
'https://plantuml.com/class-diagram

class ListManager {
    main()
    start()
}

class ListController {
    listDiplay : TextField

    selectListButtonClicked()
    addListButtonClicked()
    removeListButtonClicked()
    addItemButtonClicked()
    saveButtonClicked()
    loadButtonClicked()
    removeItemButtonClicked()
    editItemButtonClicked()

}

javafx.Application <|-- ListManager

ListManager - ListController
@enduml